name: Testhis
favicon: null
layout_spectrum: 0.022698899498209357
typography_spectrum: 0.3093257313594222
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8820046137552708
  lightness: 0.6133185403887182
  saturation: 0.2538177303504199
  rhythmicContrast: 0.447735738940537
purpose: []
